apiVersion: v1
kind: ConfigMap
metadata:
  name: prescription-service-config
  namespace: healthcare
data:
  SERVICE_NAME: "prescription-service"
  SERVICE_PORT: "8003"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  MONGO_DATABASE: "prescription_db"
  RABBITMQ_EXCHANGE: "healthcare"
  RABBITMQ_QUEUE: "prescription_queue"
  API_V1_PREFIX: "/api/v1"
  PATIENT_SERVICE_URL: "http://patient-service.healthcare.svc.cluster.local:8001"
  APPOINTMENT_SERVICE_URL: "http://appointment-service.healthcare.svc.cluster.local:8002"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  JWT_ALGORITHM: "HS256"
