apiVersion: v1
kind: Secret
metadata:
  name: prescription-service-secret
  namespace: healthcare
type: Opaque
stringData:
  MONGO_URL: "mongodb://admin:mongo_secure_password@prescription-mongo.healthcare.svc.cluster.local:27017/prescription_db?authSource=admin"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  RABBITMQ_URL: "amqp://admin:rabbitmq_secure_password@rabbitmq.healthcare.svc.cluster.local:5672/"
  REDIS_URL: "redis://:redis_secure_password@redis.healthcare.svc.cluster.local:6379/2"
---
apiVersion: v1
kind: Secret
metadata:
  name: prescription-mongo-secret
  namespace: healthcare
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongo_secure_password"
